Theta
arfc/rollo pull request #22
Opened 2022-02-28 19:57 UTC by gwenchee

2022-02-28 20:08 UTC, samgdotson reviewed
I don't have any serious comments on this, besides pointing out that there are some open issues that this PR doesn't seem to address.

2022-02-28 20:08 UTC, samgdotson commented on rollo/toolbox_generator.py
> +                weight_list.append(-wt)
A good clean change, does this fix a bug?

2022-02-28 20:09 UTC, samgdotson commented
Oh, also the CI fails.

2022-02-28 20:16 UTC, samgdotson commented
I tried creating a commit to your github action -- I think all you need to do is append `unit_tests/` to each of your pytest calls. My attempt at a PR to your fork got rejected for some reason.

2022-02-28 20:30 UTC, smpark7 requested changes
This is a basic review for code clealiness. Good job! Your code looks mostly clean. In addition to the comments, I would suggest adding print statements in input_validation to inform the user of whichever parameters were initialized to default values (if you haven't already done this).

2022-02-28 20:30 UTC, smpark7 commented on rollo/algorithm.py
>          list
Should this be `pop : list` instead?

2022-02-28 20:30 UTC, smpark7 commented on rollo/algorithm.py
>          list
Should this be `pop : list`?

2022-02-28 20:30 UTC, smpark7 commented on rollo/algorithm.py
>          # evaluate fitness of newly created pop for inds with invalid fitness
Update doc comment here.

2022-02-28 20:30 UTC, smpark7 commented on rollo/algorithm.py
> +        pop = self.apply_selection_operator(pop+offspring)
Add comment here if necessary

2022-02-28 20:30 UTC, smpark7 commented on rollo/backend.py
>                      pass
If this is intended behavior, you may wanna add a print statement here stating that it passed and why. If you're gonna implement smth here in future, then possibly add a `# TODO: ...` comment.

2022-02-28 20:30 UTC, smpark7 commented on rollo/executor.py
> +            except BaseException:
It may be helpful to add a print statement here too, to indicate that the exception occurred

2022-03-03 22:13 UTC, pep8speaks commented
Hello @gwenchee! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`rollo/backend.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/backend.py):

> [Line 9:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/backend.py#L9): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

* In the file [`rollo/constraints.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/constraints.py):

> [Line 124:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/constraints.py#L124): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 79 characters)

* In the file [`rollo/evaluation.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py):

> [Line 88:38](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L88): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 99:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L99): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 104:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L104): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 116:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L116): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 130:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L130): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 177:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L177): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 193:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L193): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 201:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L201): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 295:17](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L295): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 305:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L305): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 313:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L313): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 315:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L315): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 318:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L318): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 346:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/evaluation.py#L346): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)



* In the file [`rollo/input_validation.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/input_validation.py):

> [Line 385:15](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/input_validation.py#L385): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace





* In the file [`rollo/toolbox_generator.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/toolbox_generator.py):

> [Line 40:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/rollo/toolbox_generator.py#L40): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

* In the file [`tests/integration_tests/input_test_files/input_test_ackley.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_ackley.py):

> [Line 12:14](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_ackley.py#L12): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`tests/integration_tests/input_test_files/input_test_ackley_output.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_ackley_output.py):

> [Line 2:11](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_ackley_output.py#L2): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 8:16](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_ackley_output.py#L8): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 8:25](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_ackley_output.py#L8): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`tests/integration_tests/input_test_files/input_test_binh.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_binh.py):

> [Line 8:28](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_binh.py#L8): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`tests/integration_tests/input_test_files/input_test_binh_output.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_binh_output.py):

> [Line 2:11](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_binh_output.py#L2): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 8:12](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/input_test_files/input_test_binh_output.py#L8): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`tests/integration_tests/test_ackley_integration.py`](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/test_ackley_integration.py):

> [Line 1:10](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/test_ackley_integration.py#L1): [E401](https://duckduckgo.com/?q=pep8%20E401) multiple imports on one line
> [Line 1:30](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/test_ackley_integration.py#L1): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 4:1](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/test_ackley_integration.py#L4): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 10:80](https://github.com/arfc/rollo/blob/520e4c87aa6d96c9368ba508810da0e791b56421/tests/integration_tests/test_ackley_integration.py#L10): [E5 [...]

2022-07-14 17:56 UTC, closed without merging