Evaluator function implementation to enable job control parallelization
arfc/rollo pull request #38
Opened 2022-03-16 04:08 UTC by gwenchee

In this PR, I made the following **major changes**
1) Removed MPI dependencies since I no longer use them. Changes reflected in 
- `algorithm.py`
2) #31 and named the method `job_control` for user input. Changes reflected in 
- `algorithm.py`
- `evaluation.py`'s `eval_fn_generator` function.
- `executor.py`
- `input_validation.py`
3) Added new functions to `evaluation.py` to enable both evaluator function implementations to use them to minimize code repetition. I also added corresponding unit tests for each function. Changes reflected in: 
 - `evaluation.py`
 - `test_evaluation.py`
 - `input_test_run_execute.py`
 - `input_test_run_input_script.py`
4) #32 . Changes reflected in 
- `input_validation.py`
- `evaluation.py`

**Minor changes** 
a) Updated the integration tests to use the new input parameter names and conventions implemented in 2) and 4) 
- `input_test_ackley.json`
- `input_test_ackley_job_control.json`
- `input_test_ackley_output.py`
- `input_test_binh.json`
- `input_test_binh_job_control.json`
- `input_test_binh_output.py`
- `test_ackley_integration.py`
- `test_binh_korn.py`
- `test_executor.py`
Minor changes 
b) Moved toolbox and creator generation in unit tests to an init function so that it doesn't affect other unit tests. 
- `test_algorithm.py`
- `test_backend.py`

2022-03-16 18:23 UTC, smpark7 requested changes
Your changes are mostly well-documented. Other than my suggested changes, will you be adding tests involving moltres inputs/outputs?

2022-03-16 18:23 UTC, smpark7 commented on tests/unit_tests/input_test_files/input_test_run_execute.py
> +print([5, 6])
This file isn't automatically generated by your unit tests?

2022-03-16 18:23 UTC, smpark7 commented on tests/unit_tests/input_test_files/input_test_run_input_script.py
> +print([{{hi}}, {{hi2}}])
Was this also generated by your unit tests?

2022-03-16 18:23 UTC, smpark7 commented on rollo/evaluation.py
> +        self.supported_solvers = ["openmc", "openmc_gc", "moltres"]
What's the difference between openmc and openmc_gc?

2022-03-16 20:56 UTC, gwenchee commented on rollo/evaluation.py
> +        solver : str
Yeah this can be any solver, not just those 3. So I won't include this change.

2022-03-16 20:57 UTC, gwenchee commented on rollo/evaluation.py
> +            parallelization method (none, multiprocessing, job_control)
Done

2022-03-16 20:58 UTC, gwenchee commented on rollo/evaluation.py
> +        solver : str
Again, solver can be any string, so i won't update this.

2022-03-16 20:58 UTC, gwenchee commented on rollo/evaluation.py
> +        solver : str
Again, solver can be any string, so i won't update this.

2022-03-16 20:58 UTC, gwenchee commented on rollo/evaluation.py
> +        solver : str
Again, solver can be any string, so i won't update this.

2022-03-16 20:58 UTC, gwenchee commented on rollo/evaluation.py
> +        solver : str
Again, solver can be any string, so i won't update this.

2022-03-16 21:00 UTC, gwenchee commented on rollo/evaluation.py
> +        self.supported_solvers = ["openmc", "openmc_gc", "moltres"]
Ignore these supported solvers, I will remove them in #35. It is legacy code from an earlier version of ROLLO. I had openmc_gc to indicate that this openmc version would create group constants for Moltres, and hard coded some special functionality for it. I am moving towards a nuclear code-agnostic rollo

2022-03-16 21:04 UTC, gwenchee commented on rollo/evaluation.py
> +            empty list of the correct size
Done

2022-03-16 21:09 UTC, gwenchee commented on rollo/evaluation.py
> +                firstline = fp.readlines()[0]
DOne

2022-03-16 21:10 UTC, gwenchee commented on tests/unit_tests/input_test_files/input_test_run_execute.py
> +print([5, 6])
Nope, I meant to include it

2022-03-16 21:11 UTC, gwenchee commented on tests/unit_tests/input_test_files/input_test_run_input_script.py
> +print([{{hi}}, {{hi2}}])
Nope, I meant to include it. This file is to test the templating. So, if you template it with hi = 1, hi2 = 2 and run it, it should return [1, 2]

2022-03-16 21:13 UTC, gwenchee commented on tests/unit_tests/input_test_files/input_test_run_input_script.py
> +print([{{hi}}, {{hi2}}])
I'll put in an issue to cleanup these unprofessional variable names: #39

2022-03-16 21:13 UTC, gwenchee commented
Thanks for the review @smpark7! I have addressed all your comments.

2022-03-17 21:24 UTC, smpark7 approved these changes
Okay LGTM. Thanks for addressing my comments.

2022-03-17 21:25 UTC, merged