ROLLO Website
arfc/rollo pull request #53
Opened 2022-07-14 17:51 UTC by gwenchee

This PR contains all the files for the ROLLO website. View the built website at: https://gwenchee.github.io/rollo/. Once this PR is merged, I will add a GitHub action to host the website on arfc.github.io/rollo instead. This PR addresses #8

2022-07-14 17:51 UTC, pep8speaks commented
Hello @gwenchee! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











There are currently no PEP 8 issues detected in this Pull Request. Cheers! :beers: 

##### Comment last updated at 2022-07-18 20:28:29 UTC

2022-07-14 19:14 UTC, nsryan2 commented
I'm going through the text now, the setup looks good (love Sphinx!). Something I wanted to note off the bat is that there are some parts of the website that are still under development, and, before merging, it would be a good idea to make issues for the sections that still need content (like How to Build ROLLO Documentation). Also, love the logo you ended up going with!

2022-07-14 19:19 UTC, nsryan2 commented
This is part of my review, I just didn't know where exactly to put it:
Also, something to think about is that you've got information on installation and stuff in the top-level readme and you can import that directly into your docs with `.. mdinclude:: ../README.md` so you don't have to update multiple places.

2022-07-14 19:41 UTC, nsryan2 commented
The image [docs/source/pics/ind-demonstrate.png](https://github.com/arfc/rollo/pull/53/files#diff-813d407ef75af3c82c2aca24d7b4f3be8a094cedf55ec2e2c784a61ede445bef) should probably just be a block of text. I'm not quite sure where it is in the docs, otherwise I would've commented it in-line

2022-07-14 19:57 UTC, nsryan2 approved these changes
A few comments on the text, otherwise it looks good!

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/index.rst
> +**ROLLO** is nuclear-software agnostic, and designed to easily couple to any software.
`nuclear software` in the previous sentence is ambiguous. Combine these two sentences for conciseness

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/install.rst
> +The install guide outlines the steps to install **ROLLO** on your computer.
```suggestion
The guide outlines the steps to install **ROLLO** on your computer. 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/install.rst
> +programming language. Pip installing ROLLO is the most straightforward way to install
```suggestion
programming language. Pip is the most straightforward way to install ROLLO.
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/install.rst
> +ROLLO that is built from source.
Is it possible to do this with the setup.py script?

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/motivation.rst
> +Evolutionary algorithms have been applied to nuclear reactor design optimization.
```suggestion
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/motivation.rst
> +Previously, reactor designers individually customized available evolutionary algorithm
```suggestion
Previously, nuclear reactor designers individually customized available evolutionary algorithm 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/motivation.rst
> +using evolutionary algorithms for reactor design optimization.
```suggestion
the use of evolutionary algorithms for reactor design optimization.
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/motivation.rst
> +- Parallel: Users have the two options for running ROLLO in parallel.
```suggestion
- Parallel: Users have two options for running **ROLLO** in parallel.
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/motivation.rst
> +- Reproducible: Data from every ROLLO run saves into a unique `pickled file <https://docs.python.org/3/library/pickle.html>`_.
```suggestion
- Reproducible: Data from every **ROLLO** run saves into a unique `pickled file <https://docs.python.org/3/library/pickle.html>`_.
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/theory.rst
> +execution from beginning to end. The Executor calls `InputValidation`` to parse
```suggestion
execution from beginning to end. The Executor calls `InputValidation` to parse 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/theory.rst
> +``evaluators`` specifications in the input file. It uses the `Evaluation`` object to
```suggestion
``evaluators`` specifications in the input file. It uses the `Evaluation` object to 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/theory.rst
> +object accepts the `Evaluation` object and registers it as the toolbox's 'evaluate'
```suggestion
object accepts the `Evaluation` object and registers it as the toolbox's `evaluate`
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/checkpoint_rollo.rst
> +Therefore, if you're running a ROLLO simulation with 10 generations and it fails
```suggestion
Therefore, if you're running a **ROLLO** simulation with 10 generations and it fails 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/checkpoint_rollo.rst
> +during generation 3, you can restart the ROLLO simulation from generation 2.
```suggestion
during generation 3, you can restart the **ROLLO** simulation from generation 2. 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/checkpoint_rollo.rst
> +     - fitness tuple holds the objective values. The sign refers to whether the objective is maximize or minimize.
```suggestion
     - fitness tuple holds the objective values. The sign refers to whether the objective is to maximize or minimize. 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/checkpoint_rollo.rst
> +     - tuple of reactor model individual's output parameters
```suggestion
     - tuple of reactor model individual output parameters
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/parallel_rollo.rst
> +The serial run mode runs each reactor model in each generation serially.
```suggestion
The serial run mode runs each reactor model in each generation in series. 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/parallel_rollo.rst
> +The multiprocessing_on_dill map chops the iterable into several chunks which it
```suggestion
The `multiprocessing_on_dill` map chops the iterable into several chunks which it 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/parallel_rollo.rst
> +The serial run mode utilizes a map() function to run the nuclear software for each
```suggestion
The serial run mode utilizes a `map()` function to run the nuclear software for each 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/parallel_rollo.rst
> +The multiprocessing mode replaces the default map function with the
```suggestion
The multiprocessing mode replaces the default `map()` function with the 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/parallel_rollo.rst
> +This mode does not use the map() function.
```suggestion
This mode does not use the `map()` function. 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/run_rollo.rst
> +For each run, **ROLLO** will output a txt file with the terminal output from the run.
```suggestion
For each run, **ROLLO** will output a .txt file with the terminal output from the run. 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/run_rollo.rst
> +named OpenMC and the input script, the txt file will be named
```suggestion
named OpenMC and the input script, the .txt file will be named 
```

2022-07-14 19:57 UTC, nsryan2 commented on docs/source/usersguide/run_rollo.rst
> +After each ROLLO generation runs, ROLLO will output the following table with details about
```suggestion
After each **ROLLO** generation runs, **ROLLO** will output the following table with details about 
```

2022-07-14 20:43 UTC, samgdotson requested changes
Nathan had some good comments. These are extremely minor changes. The website looks phenomenal -- you've done an excellent job and should be very proud, @gwenchee!

2022-07-14 20:43 UTC, samgdotson commented on docs/source/about_us.rst
> +Recommended publication for citing
Gwen, if you have time I would recommend submitting a paper to [JOSS](https://joss.theoj.org/). They're pretty lightweight articles that just explain the need and the software -- which you have basically done with your prelim/thesis.

2022-07-14 20:43 UTC, samgdotson commented on docs/source/install.rst
> +The install guide outlines the steps to install **ROLLO** on your computer.
```suggestion
The installation guide outlines the steps to install **ROLLO** on your computer. 
```

@nsryan2 your suggestion is fine, though "the" guide suggests a singular manual -- this is just for installing.

2022-07-14 20:43 UTC, samgdotson commented on docs/source/install.rst
> +Install Guide
```suggestion
Installation Guide
```

2022-07-14 20:43 UTC, samgdotson commented on docs/source/install.rst
> +it.
```suggestion
```

Use this with @nsryan2's suggestion.

2022-07-14 20:43 UTC, samgdotson commented on docs/source/install.rst
> +ROLLO that is built from source.
@gwenchee I'm not sure if Mac OS X is different (I doubt it is), but if you add a `requirements.txt` file. Users can simply do `pip install -r requirements.txt`, which installs all of the packages automatically. Alternatively, you can write a command in the guide for them to copy and paste. E.g.
```bash
pip install deap jinja2 numpy jsonschema pytest
```
which would accomplish the same thing.

2022-07-14 23:35 UTC, yardasol commented
@gwenchee this website looks great! I'll do a proper review tomorrow morning hopefully.

2022-07-14 23:46 UTC, nsryan2 commented on docs/source/install.rst
> +ROLLO that is built from source.
Can confirm that works on Mac!

2022-07-15 16:20 UTC, gwenchee commented
Wow! Thanks all @nsryan2 @samgdotson @yardasol  for such fast reviews! I'll address your comments shortly. Also, in this PR I included example notebooks which you can view here: https://github.com/arfc/rollo/wiki/Example-Jupyter-Notebooks/ , let me know if you have any comments about these as well.

2022-07-15 17:19 UTC, gwenchee commented on docs/source/index.rst
> +**ROLLO** is nuclear-software agnostic, and designed to easily couple to any software.
done

2022-07-15 17:21 UTC, gwenchee commented on docs/source/about_us.rst
> +Recommended publication for citing
Thanks for the suggestion, Sam! I plan to write a long paper describing ROLLO and the AHTR optimization I did for my dissertation. I'll discuss with Madicken if a JOSS paper makes sense as well.

2022-07-15 18:24 UTC, gwenchee commented on docs/source/install.rst
> +ROLLO that is built from source.
Done!

2022-07-15 18:30 UTC, gwenchee commented
Thanks, @nsryan2 and @samgdotson! I have addressed all your inline comments. As per your suggestions, I added a `requirements.txt` to ease the dependency install process and updated the docs to reflect it. 

@nsryan2 : 
>  it would be a good idea to make issues for the sections that still need content (like How to Build ROLLO Documentation).

I created #53 to address this. 

> Also, something to think about is that you've got information on installation and stuff in the top-level readme and you can import that directly into your docs with `.. mdinclude:: ../README.md` so you don't have to update multiple places. You can do the same thing with a contributing document so that it can exist in your repo separate from the docs and in your docs!

This is a great suggestion, but I decided not to do this since I don't want to make the README too bloated with information. Instead, I provide a brief description about installing and running ROLLO in the README with links to the docs. 

I also updated the figures you mentioned into text. I was being lazy, so I'm glad you pointed them out :)

2022-07-15 19:40 UTC, samgdotson approved these changes
Thanks for addressing our comments!

2022-07-15 20:48 UTC, yardasol approved these changes
Hi @gwenchee. It's a lot of work getting a website set up so I just want to recognize that I think you did an absolutely fantastic job on this. I have a few comments I'd like you to consider. See them below.

Also, please add python API docs for ROLLO to the website before moving it to arfc.github.io

2022-07-15 20:48 UTC, yardasol commented on .github/workflows/build-website.yml
> +        directory: ./docs/build/html
instead of force pushing (not a great practice), consider using [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) to deploy the site for you

2022-07-15 20:48 UTC, yardasol commented on docs/source/devguide/build_docs.rst
> +================================
Just add the commands you use in your actions workflow file.

2022-07-15 20:48 UTC, yardasol commented on docs/source/index.rst
> +   License <https://github.com/arfc/rollo/blob/main/LICENSE/>
I'd strongly recommend adding API docs so users and developers don't have to dive into source files to explore the code.

2022-07-15 20:48 UTC, yardasol commented on docs/source/motivation.rst
> +packages for their reactor design optimization problems.
Previously to what? This is a bit vague, consider adding some citations or extra descriptions of previous efforts.

2022-07-15 20:48 UTC, yardasol commented on docs/source/motivation.rst
> +the use of evolutionary algorithms for reactor design optimization.
Move this to the top of the motivation section

2022-07-15 20:48 UTC, yardasol commented on docs/source/motivation.rst
> +the use of evolutionary algorithms for reactor design optimization.
```suggestion
The motivation for **ROLLO** is to provide a user-friendly tool that helps reactor designers use evolutionary algorithms for reactor design optimization.
```

2022-07-15 20:48 UTC, yardasol commented on docs/source/theory.rst
> +nuclear reactor design.
```suggestion
**ROLLO** provides a framework to couple an evolutionary algorithm driver with nuclear 
software, such as neutron transport and thermal-hydraulics codes, to optimize 
nuclear reactor design. 
```

2022-07-15 20:48 UTC, yardasol commented on docs/source/theory.rst
> +       5) Genetic algorithm execution with Algorithm
This is fine, but again, I'd strongly recommend having API docs available on website before it gets moved to arfc.github.io

2022-07-15 20:48 UTC, yardasol commented on docs/source/usersguide/checkpoint_rollo.rst
> +If the **ROLLO** simulation fails half way through a generation, the user can
```suggestion
If the **ROLLO** simulation fails during a generation, the user can
```

2022-07-15 20:48 UTC, yardasol commented on docs/source/usersguide/checkpoint_rollo.rst
> +file to restart the code from the most recent population and continue the simulation.
```suggestion
file.
```

You can delete this since it's repeated immediately after

2022-07-15 20:48 UTC, yardasol commented on docs/source/usersguide/checkpoint_rollo.rst
> +Each reactor model individual is an Ind class type with attributes and is a simple
```suggestion
Each reactor model individual is an :class:`Ind` class type with attributes and is a simple 
```

2022-07-15 20:48 UTC, yardasol commented on docs/source/usersguide/run_rollo.rst
> +``population size`` (more description in :ref:`input file algorithm section
```suggestion
``pop_size`` (more description in :ref:`input file algorithm section 
```

2022-07-15 20:48 UTC, yardasol commented on docs/source/usersguide/setup_rollo.rst
> +     - yes
In the future, it may make sense to move your JSON schema to an external file so you can import it here into the docs. It will reduce the amount of things you need to change if your JSON schema changes. You can do this using the `sphinx-jsonschema` package.

2022-07-18 18:09 UTC, gwenchee commented on .github/workflows/build-website.yml
> +        directory: ./docs/build/html
This is great, thanks @yardasol , I implemented it.

2022-07-18 18:17 UTC, gwenchee commented on docs/source/devguide/build_docs.rst
> +================================
Done

2022-07-18 18:19 UTC, gwenchee commented on docs/source/motivation.rst
> +packages for their reactor design optimization problems.
I removed it instead.

2022-07-18 18:24 UTC, gwenchee commented
@yardasol Thanks for the review! Based on your comments, I made the following updates to the PR. 

1) I have implemented your excellent suggestion for Python API. 
2) I addressed #54 by adding the commands you use in your actions workflow file.
3) > In the future, it may make sense to move your JSON schema to an external file so you can import it here into the docs. It will reduce the amount of things you need to change if your JSON schema changes. You can do this using the `sphinx-jsonschema` package.
I added #56 and #57 to address this in a future PR. 



Here's the built website link again for convenience: https://gwenchee.github.io/rollo/

2022-07-18 19:09 UTC, yardasol approved these changes
Thanks for addressing my comments @gwenchee. I saw a few more things in the second pass, but mostly all the changes look good.

I'd recommend adding formatting to variable, function, and class names in the docstrings for your classes and functions so they render with styling and can be easily differentiated from normal text on the web-hosted API docs. This is a lot of work though so may be better suited for a new PR.

2022-07-18 19:09 UTC, yardasol commented on .github/workflows/build-website.yml
> +        # sphinx-apidoc -f -o docs/source . -H Test -e -t docs/source/_templates
```suggestion
```
You shouldn't need to run `make clean` since this is the base repo (with no build files in it). Also don't need a commented out line.

2022-07-18 19:09 UTC, yardasol commented on .github/workflows/build-website.yml
> +    - name: make the sphinx docs
```suggestion
    - name: Make the sphinx docs
```

2022-07-18 19:09 UTC, yardasol commented on .github/workflows/build-website.yml
> +    - name: Deploy
```suggestion
    - name: Deploy docs to github pages
```

2022-07-18 19:09 UTC, yardasol commented on .github/workflows/build-website.yml
> +        publish_dir: ./docs/build/html
```suggestion
        publish_dir: ./docs/build/html
        commit_message: "update docs at commit: ${{ github.event.head_commit.message }}"
```
Might be a good idea to add a commit so you can track the progression of the `gh-pages` branch in the source tree.

2022-07-18 19:09 UTC, yardasol commented on .github/workflows/build-website.yml
> +      if: ${{ github.ref == 'refs/heads/docs' }}
```suggestion
```
I don't think you need this if-statement, but if you've tested it and the docs only build with it present, then leave it in the workflow file.

2022-07-18 19:09 UTC, yardasol commented on .github/workflows/build-website.yml
> +    - uses: actions/checkout@v2
```suggestion
    - uses: actions/checkout@v3
```
Use newest version

2022-07-18 19:09 UTC, yardasol commented on .github/workflows/build-website.yml
> +      uses: actions/setup-python@v2
```suggestion
      uses: actions/setup-python@v4
```

2022-07-18 19:09 UTC, yardasol commented on docs/source/devguide/build_docs.rst
> +    make latexpdf
great work!

2022-07-18 19:09 UTC, yardasol commented on docs/source/index.rst
> +   autoapi/index
:)

2022-07-18 19:09 UTC, yardasol commented on docs/source/motivation.rst
> +The motivation for **ROLLO** is to provide a user-friendly tool that helps reactor designers use evolutionary algorithms for reactor design optimization.
Make the sentence on line 20 the first sentence in the Motivation section.

2022-07-18 19:09 UTC, yardasol commented on docs/source/motivation.rst
> +The evolutionary algorithm setup is highly customizable with an assortment of
```suggestion
Evolutionary algorithm setup is highly customizable with an assortment of 
```

2022-07-18 19:09 UTC, yardasol commented on docs/source/index.rst
> +It essentially couples the `DEAP (Distributed Evolutionary Algorithms in Python)
```suggestion
It couples the `DEAP (Distributed Evolutionary Algorithms in Python) 
```

2022-07-18 20:28 UTC, gwenchee commented on docs/source/motivation.rst
> +The motivation for **ROLLO** is to provide a user-friendly tool that helps reactor designers use evolutionary algorithms for reactor design optimization.
Done

2022-07-18 20:31 UTC, gwenchee commented
Thanks @yardasol !

> I'd recommend adding formatting to variable, function, and class names in the docstrings for your classes and functions so they render with styling and can be easily differentiated from normal text on the web-hosted API docs. This is a lot of work though so may be better suited for a new PR.

I opened #58. 

The PR is ready to be merged @nsryan2 @samgdotson @yardasol

2022-07-18 20:51 UTC, merged